services :
    api:
        image: canals/php:latest
        volumes:
            - ./api:/var/www/html
        ports:
            - 8080:80
        restart: always
    db:
        image: mysql:5.7
        volumes:
            - ./db:/var/lib/mysql
        ports:
            - 3306:3306
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: root
            MYSQL_PASSWORD: root

    front_admin:
        build :
            context: .
            dockerfile: Dockerfile
        working_dir: /app
        volumes:
            - ./front_admin:/app
            - ./front_admin/node_modules
        ports:
            - 8081:8080

        command: npm install && npm run dev

    front_client:
        build :
            context: .
            dockerfile: Dockerfile
        image: node:latest
        working_dir: /app
        volumes:
            - ./front_client:/app
            - ./front_client/node_modules
        ports:
            - 8082:8080

        command : npm install && npm run dev

    adminer :
        image: adminer
        ports:
            - 8083:8080
        restart: always